# Template für Home Assistant Entity Sensoren
# Wird mehrfach mit unterschiedlichen vars eingebunden
# Variablen: num, entity_id, default_icon

defaults:
  num: "1"
  entity_id: "switch.placeholder"
  default_icon: "mdi:lightbulb"

binary_sensor:
  - platform: homeassistant
    id: ha_entity_state_${num}
    entity_id: ${entity_id}
    internal: true
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: homeassistant_btn_${num}
          state:
            checked: !lambda return x;

text_sensor:
  # Friendly Name für Button Label
  - platform: homeassistant
    id: ha_entity_${num}_friendly_name
    entity_id: ${entity_id}
    attribute: friendly_name
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_${num}_label
          text: !lambda return x.c_str();

  # Icon für Button (MDI Icons aus Home Assistant)
  # Hinweis: Das icon-Attribut ist nur gesetzt, wenn der Nutzer es manuell überschrieben hat.
  # Andernfalls verwendet Home Assistant ein Default-Icon basierend auf Domain/Device Class,
  # das aber nicht als Attribut verfügbar ist.
  - platform: homeassistant
    id: ha_entity_${num}_icon
    entity_id: ${entity_id}
    attribute: icon
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_${num}_icon
          text: !lambda |-
            static MdiIconHelper helper;
            // Bei leerem oder fehlendem Icon-Attribut -> default_icon verwenden
            if (x.empty()) {
              return helper.convert_mdi_icon("${default_icon}");
            }
            return helper.convert_mdi_icon(x);

  # Entity ID als Text Sensor (z.B. für Button Service Aufrufe)
  - platform: template
    id: ha_entity_${num}_id
    internal: true
    lambda: |-
      return {"${entity_id}"};
