# Template für Home Assistant Entity Sensoren
# Wird mehrfach mit unterschiedlichen vars eingebunden
# Variablen: num, entity_id
#
# Default Icons basieren auf Home Assistant Standards:
# https://github.com/home-assistant/frontend/blob/main/src/data/icons.ts
# Die Domain wird automatisch aus der entity_id extrahiert.

defaults:
  num: "1"
  entity_id: "switch.placeholder"

# Script für verzögerte LVGL Flag-Updates mit Retry-Logik
script:
  - id: update_button_flags_${num}
    mode: restart
    then:
      - lambda: |-
          // Warte bis zu 5 Sekunden (10 Versuche x 500ms) auf LVGL-Initialisierung
          for (int i = 0; i < 10; i++) {
            if (lv_is_initialized()) {
              auto obj = id(homeassistant_btn_${num});
              std::string domain = id(ha_entity_${num}_domain).state;
              
              if (domain == "button") {
                lv_obj_clear_flag(obj, LV_OBJ_FLAG_CHECKABLE);
                lv_obj_clear_state(obj, LV_STATE_CHECKED);
                ESP_LOGD("ha_entity", "Button ${num} flags updated: non-checkable (domain: button)");
              } else {
                lv_obj_add_flag(obj, LV_OBJ_FLAG_CHECKABLE);
                ESP_LOGD("ha_entity", "Button ${num} flags updated: checkable (domain: %s)", domain.c_str());
              }
              return;
            }
            
            // LVGL noch nicht bereit, kurz warten
            delay(500);
          }
          
          // Timeout: LVGL wurde nicht innerhalb von 5 Sekunden initialisiert
          ESP_LOGW("ha_entity", "Timeout waiting for LVGL initialization for button ${num}");

binary_sensor:
  - platform: homeassistant
    id: ha_entity_state_${num}
    entity_id: ${entity_id}
    internal: true
    trigger_on_initial_state: true
    on_state:
      then:
        - if:
            condition:
              lambda: 'return id(ha_entity_${num}_domain).state != "button";'
            then:
              - lvgl.widget.update:
                  id: homeassistant_btn_${num}
                  state:
                    checked: !lambda return x;

text_sensor:
  # Friendly Name für Button Label
  - platform: homeassistant
    id: ha_entity_${num}_friendly_name
    entity_id: ${entity_id}
    attribute: friendly_name
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_${num}_label
          text: !lambda return x.c_str();

  # Icon für Button (MDI Icons aus Home Assistant)
  # Hinweis: Das icon-Attribut ist nur gesetzt, wenn der Nutzer es manuell überschrieben hat.
  # Andernfalls verwendet Home Assistant ein Default-Icon basierend auf Domain/Device Class,
  # das aber nicht als Attribut verfügbar ist.
  # Wir ermitteln das Domain-Default-Icon automatisch aus der entity_id.
  - platform: homeassistant
    id: ha_entity_${num}_icon
    entity_id: ${entity_id}
    attribute: icon
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_${num}_icon
          text: !lambda |-
            static MdiIconHelper helper;
            // Bei gesetztem Icon-Attribut -> dieses verwenden
            if (!x.empty()) {
              return helper.convert_mdi_icon(x);
            }
            // Andernfalls Domain-spezifisches Default-Icon verwenden
            return id(ha_entity_${num}_default_icon).state;

  # Default Icon basierend auf Entity Domain (wird bei Initialisierung gesetzt)
  - platform: template
    id: ha_entity_${num}_default_icon
    internal: true
    lambda: |-
      static MdiIconHelper helper;
      std::string entity_id = "${entity_id}";
      std::string domain = entity_id.substr(0, entity_id.find('.'));
      
      // Home Assistant Default Icons pro Domain
      // Quelle: https://github.com/home-assistant/frontend/blob/main/src/data/icons.ts
      if (domain == "switch") return helper.convert_mdi_icon("mdi:toggle-switch-variant");
      if (domain == "light") return helper.convert_mdi_icon("mdi:lightbulb");
      if (domain == "sensor") return helper.convert_mdi_icon("mdi:eye");
      if (domain == "binary_sensor") return helper.convert_mdi_icon("mdi:radiobox-blank");
      if (domain == "input_boolean") return helper.convert_mdi_icon("mdi:toggle-switch");
      if (domain == "button") return helper.convert_mdi_icon("mdi:button-pointer");
      if (domain == "lock") return helper.convert_mdi_icon("mdi:lock");
      if (domain == "cover") return helper.convert_mdi_icon("mdi:window-shutter");
      if (domain == "fan") return helper.convert_mdi_icon("mdi:fan");
      if (domain == "climate") return helper.convert_mdi_icon("mdi:thermostat");
      if (domain == "vacuum") return helper.convert_mdi_icon("mdi:robot-vacuum");
      if (domain == "media_player") return helper.convert_mdi_icon("mdi:speaker");
      if (domain == "scene") return helper.convert_mdi_icon("mdi:palette");
      if (domain == "script") return helper.convert_mdi_icon("mdi:script-text");
      if (domain == "automation") return helper.convert_mdi_icon("mdi:robot");
      if (domain == "humidifier") return helper.convert_mdi_icon("mdi:air-humidifier");
      if (domain == "siren") return helper.convert_mdi_icon("mdi:bullhorn");
      if (domain == "valve") return helper.convert_mdi_icon("mdi:pipe-valve");
      if (domain == "alarm_control_panel") return helper.convert_mdi_icon("mdi:shield");
      if (domain == "camera") return helper.convert_mdi_icon("mdi:video");
      if (domain == "person") return helper.convert_mdi_icon("mdi:account");
      if (domain == "device_tracker") return helper.convert_mdi_icon("mdi:account");
      if (domain == "water_heater") return helper.convert_mdi_icon("mdi:water-boiler");
      if (domain == "update") return helper.convert_mdi_icon("mdi:package");
      
      // Fallback für unbekannte Domains
      return helper.convert_mdi_icon("mdi:help-circle");
    on_value:
      then:
        # Setze Default-Icon initial auf Button (wird von ha_entity_icon überschrieben wenn vorhanden)
        - if:
            condition:
              lambda: 'return id(ha_entity_${num}_icon).state.empty();'
            then:
              lvgl.label.update:
                id: homeassistant_btn_${num}_icon
                text: !lambda return x.c_str();

  # Entity State als Text Sensor (z.B. für Lock Toggle Logic)
  - platform: homeassistant
    id: ha_entity_${num}_state_text
    entity_id: ${entity_id}
    internal: true

  # Entity ID als Text Sensor (z.B. für Button Service Aufrufe)
  - platform: template
    id: ha_entity_${num}_id
    internal: true
    lambda: |-
      return {"${entity_id}"};

  # Entity Domain als Text Sensor (z.B. für Icon Auswahl)
  - platform: template
    id: ha_entity_${num}_domain
    internal: true
    lambda: |-
      std::string entity_id = "${entity_id}";
      size_t dot_pos = entity_id.find('.');
      
      // Validierung: Entity-ID muss einen Punkt enthalten
      if (dot_pos == std::string::npos) {
        ESP_LOGW("ha_entity", "Invalid entity_id format '%s': missing dot separator", entity_id.c_str());
        return std::string("unknown");
      }
      
      std::string domain = entity_id.substr(0, dot_pos);
      return domain;
    on_value:
      then:
        - script.execute: update_button_flags_${num}
