globals:
  - id: ha_connected
    type: bool
    initial_value: 'false'

esphome:
  on_boot:
    - priority: 400
      then:
        - script.execute: update_loading_page

lvgl:
  top_layer:
    widgets:
      # ========================================================================
      # BOOTSCREEN - Modern Glassmorphism Design
      # ========================================================================
      - obj:
          id: loading_page
          bg_color: color_bg_dark
          bg_opa: COVER
          shadow_opa: transp
          width: ${display_width}
          height: ${display_height}
          outline_width: 0
          border_width: 0
          radius: 0
          widgets:
            # Logo mit mehr Padding nach oben
            - image:
                y: 60
                align: top_mid
                src: ha_img
            
            # Status Container - Glassmorphism Card
            - obj:
                id: boot_homeassistant
                y: 200
                width: 340
                height: 140
                pad_all: 24
                align: top_mid
                radius: 24
                bg_color: color_gray_800
                bg_opa: 50%
                border_color: color_gray_600
                border_width: 1
                border_opa: 20%
                shadow_width: 20
                shadow_ofs_y: 8
                shadow_color: color_black
                shadow_opa: 30%
                scrollbar_mode: "OFF"
                layout:
                  type: GRID
                  grid_columns: [FR(1)]
                  grid_rows: [SIZE_CONTENT, 16, SIZE_CONTENT]
                widgets:
                  - label:
                      id: boot_homeassistant_label
                      grid_cell_column_pos: 0
                      grid_cell_row_pos: 0
                      grid_cell_x_align: CENTER
                      grid_cell_y_align: CENTER
                      text_font: roboto24
                      text_color: color_text_dark_primary
                      text: "Verbinde..."
                  - spinner:
                      id: boot_homeassistant_spinner
                      grid_cell_column_pos: 0
                      grid_cell_row_pos: 2
                      grid_cell_x_align: CENTER
                      grid_cell_y_align: CENTER
                      width: 48
                      height: 48
                      spin_time: 1500ms
                      arc_length: 90deg
                      arc_width: 4
                      arc_color: color_gray_700
                      indicator:
                        arc_color: color_primary
                        arc_width: 4
            
            # Sync Container - Glassmorphism Card
            - obj:
                id: boot_synchronization
                y: 200
                width: 340
                height: 120
                pad_all: 24
                align: top_mid
                radius: 24
                bg_color: color_gray_800
                bg_opa: 50%
                border_color: color_gray_600
                border_width: 1
                border_opa: 20%
                shadow_width: 20
                shadow_ofs_y: 8
                shadow_color: color_black
                shadow_opa: 30%
                hidden: true
                scrollbar_mode: "OFF"
                layout:
                  type: GRID
                  grid_columns: [FR(1)]
                  grid_rows: [SIZE_CONTENT, 24, SIZE_CONTENT]
                widgets:
                  - label:
                      id: boot_synchronization_label
                      grid_cell_column_pos: 0
                      grid_cell_row_pos: 0
                      grid_cell_x_align: CENTER
                      grid_cell_y_align: CENTER
                      text_font: roboto24
                      text_color: color_text_dark_primary
                      text: "Synchronisiere..."
                  - bar:
                      id: boot_synchronization_bar
                      grid_cell_column_pos: 0
                      grid_cell_row_pos: 2
                      grid_cell_x_align: CENTER
                      grid_cell_y_align: CENTER
                      width: 280
                      height: 8
                      value: 0
                      min_value: 0
                      max_value: 100
                      animated: true
                      radius: 4
                      bg_color: color_gray_700
                      bg_opa: 60%
                      indicator:
                        radius: 4
                        bg_color: color_primary
                        bg_grad_color: color_primary_light
                        bg_grad_dir: HOR


script:

  - id: update_loading_page
    then:
      - lvgl.widget.hide: navigation_bar
      - lvgl.label.update:
          id: boot_synchronization_label
          text: "Synchronisiere..."
      - lvgl.label.update:
          id: boot_homeassistant_label
          text: "Verbinde Home Assistant..."

  - id: check_boot_status
    then:
      - lambda: |-
          if (id(ha_connected)) {
            lv_obj_add_flag(id(boot_homeassistant), LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(id(boot_synchronization), LV_OBJ_FLAG_HIDDEN);
            id(start_sync_animation).execute();
          }

  - id: start_sync_animation
    then:
      - delay: 1s
      - lvgl.bar.update:
          id: boot_synchronization_bar
          value: 25

      - delay: 1s
      - lvgl.bar.update:
          id: boot_synchronization_bar
          value: 50

      - delay: 1s
      - lvgl.bar.update:
          id: boot_synchronization_bar
          value: 75

      - delay: 1s
      - lvgl.bar.update:
          id: boot_synchronization_bar
          value: 100

      - delay: 1s
      - lvgl.widget.hide: loading_page
      - lambda: 'id(current_page_index) = 0;'
      - lvgl.page.show:
          id: home_page
      - lvgl.widget.show: navigation_bar


  - id: on_ha_connected
    then:
      - lambda: |-
          if (!id(ha_connected)) {
            id(ha_connected) = true;
            lv_label_set_text(id(boot_homeassistant_label), "Home Assistant Connected!");
            lv_obj_add_flag(id(boot_homeassistant_spinner), LV_OBJ_FLAG_HIDDEN);
            id(check_boot_status).execute();
          }

api:
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - script.execute: update_loading_page
          - script.execute: on_ha_connected


  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - globals.set:
              id: ha_connected
              value: 'false'
