substitutions:
  # Icon Substitutions für LVGL Widgets (Fallback)
  lightbulb: "\U000F1802"
  nightbulb: "\U000F1A4D"

lvgl:
  pages:
    - id: home_page
      widgets:
        - image:
            align: CENTER
            src: see_img
        - obj: # Container mit GRID Layout für Button-Widgets
            layout:
              type: GRID
              grid_columns: [FR(1), FR(1), FR(1)]
              grid_rows: [FR(50), FR(50)]
            width: 100%
            height: 90%
            pad_all: 15
            pad_top: 22
            bg_opa: TRANSP
            border_opa: TRANSP
            widgets:
              # Buttons via Template-Include (col 0-2, row 0-1)
              - !include { file: ../templates/ha_button.yaml, vars: { num: "1", col: "0", row: "0", entity_id: ha_entity_1_id, default_icon: "$lightbulb" } }
              - !include { file: ../templates/ha_button.yaml, vars: { num: "2", col: "0", row: "1", entity_id: ha_entity_2_id, default_icon: "$nightbulb" } }
              - !include { file: ../templates/ha_button.yaml, vars: { num: "3", col: "1", row: "0", entity_id: ha_entity_3_id, default_icon: "$lightbulb" } }
              - !include { file: ../templates/ha_button.yaml, vars: { num: "4", col: "1", row: "1", entity_id: ha_entity_4_id, default_icon: "$lightbulb" } }
              - !include { file: ../templates/ha_button.yaml, vars: { num: "5", col: "2", row: "0", entity_id: ha_entity_5_id, default_icon: "$lightbulb" } }
              - !include { file: ../templates/ha_button.yaml, vars: { num: "6", col: "2", row: "1", entity_id: ha_entity_6_id, default_icon: "$lightbulb" } }
