# Globale Navigation für alle Pages
# Wird als top_layer über allen Seiten angezeigt (außer Boot/OTA)
# Modern Floating Design mit Page Name

# Page-Index für Navigation
# 0 = home_page
# 1 = switches_page
# Weitere Pages hier hinzufügen und TOTAL_PAGES anpassen

globals:
  - id: current_page_index
    type: int
    restore_value: no
    initial_value: '0'

  - id: total_pages
    type: int
    restore_value: no
    initial_value: '2'

lvgl:
  top_layer:
    widgets:
      # Navigation Bar - Modern Floating Style
      - obj:
          id: navigation_bar
          align: BOTTOM_MID
          y: -12
          width: 460
          height: 64
          radius: 20
          bg_color: color_gray_900
          bg_opa: 80%
          border_color: color_gray_600
          border_width: 1
          border_opa: 30%
          shadow_width: 16
          shadow_ofs_y: -4
          shadow_color: color_black
          shadow_opa: 40%
          pad_all: 8
          pad_left: 12
          pad_right: 12
          hidden: true
          scrollbar_mode: "OFF"
          layout:
            type: GRID
            grid_columns: [48, FR(1), 48]
            grid_rows: [FR(1)]
            pad_row: 0
            pad_column: 12
          widgets:
            # Zurück-Button (links)
            - button:
                id: nav_btn_prev
                grid_cell_column_pos: 0
                grid_cell_row_pos: 0
                grid_cell_x_align: CENTER
                grid_cell_y_align: CENTER
                width: 48
                height: 48
                radius: 14
                bg_color: color_gray_800
                bg_opa: 60%
                border_opa: TRANSP
                shadow_opa: TRANSP
                on_click:
                  then:
                    - script.execute: navigate_prev
                widgets:
                  - label:
                      id: nav_btn_prev_icon
                      align: CENTER
                      text_font: mdi_icons_40
                      text_color: color_gray_300

            # Page Name (Mitte)
            - label:
                id: page_name_label
                grid_cell_column_pos: 1
                grid_cell_row_pos: 0
                grid_cell_x_align: CENTER
                grid_cell_y_align: CENTER
                text: "Home"
                text_font: roboto24
                text_color: color_white

            # Vor-Button (rechts)
            - button:
                id: nav_btn_next
                grid_cell_column_pos: 2
                grid_cell_row_pos: 0
                grid_cell_x_align: CENTER
                grid_cell_y_align: CENTER
                width: 48
                height: 48
                radius: 14
                bg_color: color_gray_800
                bg_opa: 60%
                border_opa: TRANSP
                shadow_opa: TRANSP
                on_click:
                  then:
                    - script.execute: navigate_next
                widgets:
                  - label:
                      id: nav_btn_next_icon
                      align: CENTER
                      text_font: mdi_icons_40
                      text_color: color_gray_300

# Icons via MdiIconHelper setzen (on_boot)
esphome:
  on_boot:
    priority: -50
    then:
      - lambda: |-
          static MdiIconHelper helper;
          lv_label_set_text(id(nav_btn_prev_icon), helper.convert_mdi_icon("mdi:chevron-left").c_str());
          lv_label_set_text(id(nav_btn_next_icon), helper.convert_mdi_icon("mdi:chevron-right").c_str());

script:
  # Navigation zur vorherigen Seite
  - id: navigate_prev
    then:
      - lambda: |-
          int current = id(current_page_index);
          int total = id(total_pages);
          // Wrap-around: von 0 zurück zu letzter Seite
          current = (current - 1 + total) % total;
          id(current_page_index) = current;
      - script.execute: show_current_page

  # Navigation zur nächsten Seite
  - id: navigate_next
    then:
      - lambda: |-
          int current = id(current_page_index);
          int total = id(total_pages);
          // Wrap-around: von letzter Seite weiter zu 0
          current = (current + 1) % total;
          id(current_page_index) = current;
      - script.execute: show_current_page

  # Aktuelle Seite basierend auf Index anzeigen
  # Page-Name wird direkt hier gesetzt (Single Source of Truth)
  - id: show_current_page
    then:
      - if:
          condition:
            lambda: 'return id(current_page_index) == 0;'
          then:
            - lvgl.page.show: home_page
            - lvgl.label.update:
                id: page_name_label
                text: "Home"
          else:
            - if:
                condition:
                  lambda: 'return id(current_page_index) == 1;'
                then:
                  - lvgl.page.show: switches_page
                  - lvgl.label.update:
                      id: page_name_label
                      text: "Geräte"
                else:
                  # Fallback: Zurück zur Home-Seite
                  - lambda: 'id(current_page_index) = 0;'
                  - lvgl.page.show: home_page
                  - lvgl.label.update:
                      id: page_name_label
                      text: "Home"

  # Navigation Bar ein-/ausblenden
  - id: show_navigation
    then:
      - lvgl.widget.show: navigation_bar

  - id: hide_navigation
    then:
      - lvgl.widget.hide: navigation_bar

  # Zu bestimmter Seite navigieren (per Index)
  - id: navigate_to_page
    parameters:
      page_index: int
    then:
      - lambda: |-
          int total = id(total_pages);
          if (page_index >= 0 && page_index < total) {
            id(current_page_index) = page_index;
          }
      - script.execute: show_current_page
