# Workaround für ESPHome dev USB Serial JTAG VFS Linker-Bug (PR #13628)
# Kann entfernt werden sobald ESPHome 2026.2.x released ist
external_components:
  - source: github://pr#13628
    components: [esp32, logger]
    refresh: 1h

packages: 
  # Include all of the core configuration
  core: !include common/core.yaml
  homeassistant: !include common/homeassistant.yaml
  boot_screen: !include pages/boot.yaml
  home_page: !include pages/home.yaml
  switches_page: !include pages/switches.yaml
  temperatures_page: !include pages/temperatures.yaml
  thermostat_page: !include pages/thermostat.yaml
  ota_page: !include pages/ota.yaml
  navigation: !include pages/navigation.yaml
  theme: !include themes/modern.yaml

substitutions: !include common/substitutions.yaml
font: !include common/fonts.yaml
image: !include common/image.yaml