packages: 
  # Include all of the core configuration
  core: !include common/core.yaml
  boot_screen: !include pages/boot.yaml

substitutions: !include common/substitutions.yaml
color: !include common/colors.yaml
font: !include common/fonts.yaml
image: !include common/image.yaml