packages:
  # Include all of the core configuration
  core: !include main.yaml

esphome:
  project:
    name: ${project_name}
    version: dev # replaced by release workflow with the tagged version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://tntlarsn/Guition-ESP32-S3-4848S040/src/main.yaml@main
  import_full_config: false
# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial: