substitutions:
  # Homeassistant Entit채ten
  ha_switch_entity_id_1:       switch.shellypro3_ece334e98834_output_0
  ha_switch_entity_id_2:       switch.shellypro3_ece334e98834_output_1
  ha_switch_entity_id_3:       switch.shellypro3_ece334e98834_output_2
  ha_switch_entity_id_4:       switch.shellypro3_ece334ed6054_output_0
  ha_switch_entity_id_5:       switch.shellypro3_ece334ed6054_output_1
  ha_switch_entity_id_6:       switch.shellypro3_ece334ed6054_output_2

# Display Interne Entit채ten
binary_sensor:
  - platform: homeassistant
    id: ha_binary_sensor_1
    entity_id: ${ha_switch_entity_id_1}
    internal: true
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: homeassistant_btn_1
          state:
            checked: !lambda return x;

  - platform: homeassistant
    id: ha_binary_sensor_2
    entity_id: ${ha_switch_entity_id_2}
    internal: true
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: homeassistant_btn_2
          state:
            checked: !lambda return x;

  - platform: homeassistant
    id: ha_binary_sensor_3
    entity_id: ${ha_switch_entity_id_3}
    internal: true
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: homeassistant_btn_3
          state:
            checked: !lambda return x;

  - platform: homeassistant
    id: ha_binary_sensor_4
    entity_id: ${ha_switch_entity_id_4}
    internal: true
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: homeassistant_btn_4
          state:
            checked: !lambda return x;
  
  - platform: homeassistant
    id: ha_binary_sensor_5
    entity_id: ${ha_switch_entity_id_5}
    internal: true
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: homeassistant_btn_5
          state:
            checked: !lambda return x;

  - platform: homeassistant
    id: ha_binary_sensor_6
    entity_id: ${ha_switch_entity_id_6}
    internal: true
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: homeassistant_btn_6
          state:
            checked: !lambda return x;

text_sensor:
  # Friendly Names f체r Button Labels
  - platform: homeassistant
    id: ha_entity_1_friendly_name
    entity_id: ${ha_switch_entity_id_1}
    attribute: friendly_name
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_1_label
          text: !lambda return x.c_str();

  - platform: homeassistant
    id: ha_entity_2_friendly_name
    entity_id: ${ha_switch_entity_id_2}
    attribute: friendly_name
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_2_label
          text: !lambda return x.c_str();

  - platform: homeassistant
    id: ha_entity_3_friendly_name
    entity_id: ${ha_switch_entity_id_3}
    attribute: friendly_name
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_3_label
          text: !lambda return x.c_str();

  - platform: homeassistant
    id: ha_entity_4_friendly_name
    entity_id: ${ha_switch_entity_id_4}
    attribute: friendly_name
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_4_label
          text: !lambda return x.c_str();

  - platform: homeassistant
    id: ha_entity_5_friendly_name
    entity_id: ${ha_switch_entity_id_5}
    attribute: friendly_name
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_5_label
          text: !lambda return x.c_str();

  - platform: homeassistant
    id: ha_entity_6_friendly_name
    entity_id: ${ha_switch_entity_id_6}
    attribute: friendly_name
    internal: true              
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_6_label
          text: !lambda return x.c_str();

  # Icons f체r Buttons (MDI Icons aus Home Assistant)
  - platform: homeassistant
    id: ha_entity_1_icon
    entity_id: ${ha_switch_entity_id_1}
    attribute: icon
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_1_icon
          text: !lambda |-
            static MdiIconHelper helper;
            return helper.convert_mdi_icon(x);

  - platform: homeassistant
    id: ha_entity_2_icon
    entity_id: ${ha_switch_entity_id_2}
    attribute: icon
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_2_icon
          text: !lambda |-
            static MdiIconHelper helper;
            return helper.convert_mdi_icon(x);

  - platform: homeassistant
    id: ha_entity_3_icon
    entity_id: ${ha_switch_entity_id_3}
    attribute: icon
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_3_icon
          text: !lambda |-
            static MdiIconHelper helper;
            return helper.convert_mdi_icon(x);

  - platform: homeassistant
    id: ha_entity_4_icon
    entity_id: ${ha_switch_entity_id_4}
    attribute: icon
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_4_icon
          text: !lambda |-
            static MdiIconHelper helper;
            return helper.convert_mdi_icon(x);

  - platform: homeassistant
    id: ha_entity_5_icon
    entity_id: ${ha_switch_entity_id_5}
    attribute: icon
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_5_icon
          text: !lambda |-
            static MdiIconHelper helper;
            return helper.convert_mdi_icon(x);

  - platform: homeassistant
    id: ha_entity_6_icon
    entity_id: ${ha_switch_entity_id_6}
    attribute: icon
    internal: true
    on_value:
      then:
        lvgl.label.update:
          id: homeassistant_btn_6_icon
          text: !lambda |-
            static MdiIconHelper helper;
            return helper.convert_mdi_icon(x);